### PR TITLE
Fixing menu issues

### PR DESCRIPTION
**Pull request by martinheidegger**
## Description

In this PR I am attempting to fix the menu issues mentioned in #179. It is not quite ready as I havn't had a chance to re-add the menu insets (help appreciated)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by kinxiel — APPROVED** [review]

**Review by kinxiel — APPROVED** [review]
Aside from the `this` binding, there shouldn't be any difference between arrow function and normal function right?

**Review by kinxiel — APPROVED** [review]

**Review by kinxiel — APPROVED** [review]
Didn't know about this. Cool.

**Review by kinxiel — APPROVED** [review]

**Review by kinxiel — APPROVED** [review]

**Review by kinxiel — APPROVED** [review]
Good point.

**Review by kinxiel — APPROVED** [review]

**Review by kinxiel — APPROVED** [review]

**Comment by kinxiel** [comment]
Aside from removing the alert in what else do you think needs more work (based on the last commit)? Also what are you referring to in "menu insets"?

**Review by kinxiel — COMMENTED** [review]
Is max-width: 50em a spec for mobile?

**Comment by martinheidegger** [comment]
On Android I notice that the scroll lock doesn't work always.

I think this PR also needs to be rebased to use the new gradients.

With "insets" I mean that this PR removed `env(save-inset` Statements without a replacement.

https://github.com/owddm/owddm.github.io/pull/180/files#diff-71220bcd6e198484ebdbf2a4af5aa3261ee428037764aaa622b6c90b4fe36914L432

The "max-width: 50em" should take care both of mobile and too big desktop sizes. Basically now it just goes by how much space is available.

**Comment by kinxiel** [comment]
Oh the iPhone notch inset stuff. With the new break points, the hamburger does not need to appear on landscape on mobile, so it might not be needed, I will need to check on a smaller phone with a notch though.

**Comment by jamcgrath** [comment]
Hamburger should be a button with an accessible name instead of a `div` with a click event.

**Comment by kinxiel** [comment]
Todos:

- [x] Fix insets
- [x] Convert hamburger to button
- [x] Adjust for devices with 320 px width or smaller (280 px probably what was shown in the issue).
- [x] Adjust map coordinates, since on some devices both events do not show.

**Comment by kinxiel** [comment]
Checked the responsiveness of the menu until iPhone SE. Not sure about other smaller Android phones.

**Comment by kinxiel** [comment]
Checked responsiveness until iPhone SE but I am not sure for other smaller Android devices.

**Comment by kinxiel** [comment]
Just wondering, should the mobile menu stay in place after navigation or should it disappear when navigating to the new page?

**Comment by martinheidegger** [comment]
Let's see if it feels odd

**Pull request merged**
