### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by martinheidegger**
## Description

@jamcgrath started working on the html for the next OWDDM website following a design of @Kimmym6a. This PR contains the start of the version 2.0.

## Motivation and Context

We want to have a new website that contains links to the survey, the KWDDM and lists the meetups. This is not yet ready for publication. See the Task list below for things to be done before this can be merged.

## Open Tasks

- [ ] Link the various place to what they belong to
- [ ] Photo Display with source from Twitter
- [ ] Show the actual events as also shown on meetup.com
- [ ] Make sure that markup and code features work just as before

## Screenshot

Screenshot 2022-09-22 at 15-40-59 OWDDM _ KWDDM

### CODE REVIEW

**Comment by coliff** [comment]
The new design/layout looks neat but I suggest we just add that the `/layouts` and keep the current build system and not remove everything that is setup already.

Everything was setup nicely to lint, test, format the code and auto-deploy it minified and included sitemap, correct favicons, plausible analytics, correct meta descriptions etc and had recommended VS Code extensions for contributors and Stylelint, editorconfig files for consistent formatting etc.

**Comment by martinheidegger** [comment]
@coliff Yes, trying to get these features in there again is an open task. Note that I didn't try to throw things away just quickly prepare this PR from the data received. 😅 

[Edit]I added an issue to the description pointing out that this needs to be done as well[/Edit]

**Comment by kinxiel** [comment]
How will the site be built eventually? Not sure how the site was initially setup, but looking at some of the files looked like it was generated using a static site generator? Could someone give an overview?

**Comment by martinheidegger** [comment]
@kinxiel You can build the site right now using `npm run build` (the `npm run dev` script starts the developer mode)

**Comment by kinxiel** [comment]
Oh thanks. Are we going for minimalist HTML, CSS and Vanilla JS?

**Comment by martinheidegger** [comment]
The html is basic atm. But much is missing. The way of writing css is good imo. It uses vite to compile so -> Vue for JS

**Comment by kinxiel** [comment]
Haven't used Vue before, so might be a good opportunity to learn. Hope you can clean my mess later lol.

**Comment by martinheidegger** [comment]
Closed as we have finally merged #140

**Pull request closed without merging**
